### ISSUE TITLE
typo in params.js

### ISSUE THREAD

**Issue by avenda** [rogeriopradoj/codeigniter-composer#6]
At the repo page,the command sed has two doble quote

sed -i \"\" \"s/$system_path...

Must be:

sed -i  \"s/$system_path...

**Comment by rogeriopradoj** [comment]
Hi, @avenda , thanks for pointing this.

When you try to run this in Linux do you got problems? I used `sed` that way because in Mac OS X it is needed.

I found https://stackoverflow.com/questions/5694228/sed-in-place-flag-that-works-both-on-mac-bsd-and-linux that can fix the problem both for OS X and Linux.

Could you help me with that (I mean, sending a Pull Request with the fix)?

Thanks!
